name: cutline
description: "Skip the waiting line â€” your haircut, your time"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  firebase_remote_config: ^5.0.0
  
  # State Management
  provider: ^6.0.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # UI & Utils
  google_fonts: ^6.0.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  package_info_plus: ^8.0.0
  
  # Additional
  uuid: ^4.0.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  image_picker: ^1.0.0
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
